### ISSUE TITLE
Error spaming logs + No armour texture

### ISSUE THREAD

**Issue by QORTEC** [chbachman/ModularArmour#73]
I have the following errors is spaming my logs anytime I have my inventory opened with Modular Armour viable [in armor slot], or go in 3ed Person view [F5]

Errors:
https://gist.github.com/QORTEC/1b8974938ea5335ae265

Probably related issue/symptom:
* I crafted a set of Modular Armour and put it on [without any upgrades], and there weren't any [armour] textures applied to my character.
* [I was under the impression that the armor had textures by default and there was a camouflage upgrade to disable those Armour textures.]

**Comment by allaryin** [comment]
Confirmed on my end as well:
```
[Client thread/ERROR]: Couldn't render entity
java.lang.NullPointerException
	at chbachman.api.item.UpgradeLogic.getArmourTexture(UpgradeLogic.java:154) ~[UpgradeLogic.class:?]
	at chbachman.armour.items.armour.ItemModularArmour.getArmorTexture(ItemModularArmour.java:89) ~[ItemModularArmour.class:?]
	at net.minecraftforge.client.ForgeHooksClient.getArmorTexture(ForgeHooksClient.java:80) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.entity.RenderBiped.getArmorResource(RenderBiped.java:380) ~[bnw.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_77032_a(RenderPlayer.java:67) ~[bop.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_77032_a(RenderPlayer.java:491) ~[bop.class:?]
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:157) [boh.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:158) [bop.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521) [bop.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293) [bnn.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276) [bnn.class:?]
```

This affects the wearer of the armour when in inventory or other players who look at you, and no armour renders. Crafting the camo upgrade does not fix the problem.

**Comment by allaryin** [comment]
Just for clarification, this is running 1.0.17-40, it looks like there is at least a null check in the code since then... so this is possibly fixed in code already, just needing a new release build?

**Comment by chbachman** [comment]
Sorry about the large delay, I have been on vacation. I'm coming back on Monday, so I'll work on it then. I'm going to work on this Monday, shouldn't be a huge problem.

**Comment by chbachman** [comment]
I'm going to close this util I get verification that it is still an issue with the newest version. 

Sorry about the delay guys, I have been really busy. :)
